#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# sched-plot -- Plot a workload schedule
#
# Given a system configuration, a workload description, and a schedule as
# generated by `scorsa-sched', this program generates a plot displaying the
# amount of sockets used by each job over time, as well as submission times
# for each job in the workload.
#
# Copyright © 2018 Aaron Call <aaron.callo@bsc.es>

import sys
import logging
import argparse
import json
import copy
import math

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

logging.basicConfig(format="%(message)s", level=logging.ERROR)

ap = argparse.ArgumentParser()
#ap.add_argument("-l", "--layout", dest="l", required=True,
#                help="Layout ile (json format)")
ap.add_argument("-s", "--schedule", dest="s", required=True,
				help="JSON wl distribution file")
args = ap.parse_args()

with open(args.s) as s:
	workloads = json.load(s)

executionTimes = []
nvmeBw = []
nvmeCap = []
for i in workloads:
    executionTimes.append(i["executionTime"])
    nvmeBw.append(i["nvmeBandwidth"])
    nvmeCap.append(i["nvmeCapacity"])

plt.clf()
pl = plt.hist(executionTimes, 1500, density=False, facecolor='g', alpha=0.75, cumulative=False, histtype='step')
plt.ylabel('Probability')
plt.xlabel('Execution time')
# plt.ylim(0,1)
# plt.xticks(np.arange(0, max(executionTimes)+1, 0.5), rotation='vertical')
plt.savefig('plots/wl-distribution-exetime.pdf', bbox_inches='tight')
plt.clf()
pl = plt.hist(nvmeBw, 1500, density=False, facecolor='g', alpha=0.75, cumulative=False, histtype='step')
plt.ylabel('Probability')
plt.xlabel('NVMe Bandwidth')
# plt.xticks(np.arange(0, max(nvmeBw)+1, 0.5), rotation='vertical')
plt.savefig('plots/wl-distribution-nvmeBw.pdf', bbox_inches='tight')
plt.clf()
pl = plt.hist(nvmeCap, 1500, density=False, facecolor='g', alpha=0.75, cumulative=False, histtype='step')
plt.ylabel('Probability')
plt.xlabel('NVMe Capacity')
# plt.xticks(np.arange(0, max(nvmeCap)+1, 0.5), rotation='vertical')
plt.savefig('plots/wl-distribution-nvmeCap.pdf', bbox_inches='tight')
